spring:
  application:
    name: PUBLISHER-SERVICE
# Below configuration details pass using java config class 
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092 # indicating a Kafka server running on the local machine on port 9092
# Defines the class used to serialize the key of the message being sent. meaning the keys are serialized as strings.
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
# Defines the class used to serialize the value of the message being sent. meaning the values are serialized as strings.
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer    
server:
  port: 8081
  servlet:
    context-path: /api